FROM $IMAGE_NAME

LABEL eu.simphony-project.docker.type="webapp"

COPY container-files/ /

WORKDIR /root

# These are required for the remote access to the docker container
EXPOSE 8888
ENTRYPOINT ["/startup.sh"]
